image: Visual Studio 2017

clone_depth: 1

configuration: release

branches:
  only:
  - develop
  - master

skip_tags: true

skip_branch_with_pr: true

assembly_info:
  patch: false

# dotnet_csproj:
#   patch: true
#   file: '**\*.csproj'
#   version: '{version}'
#   assembly_version: '{version}'
#   file_version: '{version}'

install:
  - choco install gitversion.portable -pre -y
  - nuget restore

before_build:
  - pwsh: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  project: .\src\ILLightenComparer\ILLightenComparer.csproj

# after_build:
#   - cmd: ECHO nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#   - cmd: nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#   - cmd: appveyor PushArtifact "<NuSpec>.%GitVersion_NuGetVersion%.nupkg"

test:
  assemblies:
    - '**\*.tests.dll'

befor_deply:
- pwsh: |
    dotnet pack .\src\ILLightenComparer\ --include-source --include-symbols --no-build --no-dependencies
    Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName "nuget-package"

# deploy:
# - provider: Environment
#   name: appveyor-nuget
#   on:
#     branch: master
