image: Visual Studio 2017

version: 'build-{build}'

configuration: release

branches:
  only:
  - develop
  - master

skip_tags: true

skip_branch_with_pr: true

before_build:
  - pwsh: |
      dotnet restore .\src
      gitversion /l console /output buildserver /updateAssemblyInfo /verbosity warn

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  project: .\src

test:
  assemblies:
    - '**\*.tests.dll'

artifacts:
  - path: '**\*.nupkg'
    name: nuget-package
    type: NuGetPackage

deploy:
- provider: Environment
  name: appveyor-nuget
  on:
    branch: master
