image: Ubuntu1804

version: 0.1.{build}

clone_depth: 1

configuration: release

branches:
  only:
  - develop
  - master

skip_tags: true

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

environment:
  project: .\src\ILLightenComparer\ILLightenComparer.csproj

# assembly_info:
#   patch: false

dotnet_csproj:
  patch: true
  file: '{project}'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# install:
#   - choco install gitversion.portable -pre -y

# before_build:
#   - nuget restore
#   - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  project: project

deploy:
- provider: Environment
  name: appveyor-nuget
  on:
    branch: master


# after_build:
#   - cmd: ECHO nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#   - cmd: nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#   - cmd: appveyor PushArtifact "<NuSpec>.%GitVersion_NuGetVersion%.nupkg"
