image: Visual Studio 2017

version: 'build-{build}'

configuration: release

branches:
  only:
  - develop
  - master

skip_tags: true

skip_branch_with_pr: true

dotnet_csproj:
  patch: true
  file: src\ILLightenComparer\ILLightenComparer.csproj
  version: $(GitVersion_NuGetVersion)
  assembly_version: $(GitVersion_MajorMinorPatch)
  file_version: $(GitVersion_MajorMinorPatch)
  informational_version: $(GitVersion_InformationalVersion)

before_build:
- pwsh: gitversion /output buildserver /verbosity warn
- pwsh: Get-ChildItem 'env:'

build_script:
- pwsh: |
    if ($env:APPVEYOR_REPO_BRANCH -ne 'master') {
        $env:CONFIGURATION = 'debug'
    }
    dotnet build .\src -c $env:CONFIGURATION -v m
    dotnet pack .\src\ILLightenComparer\ --include-source --include-symbols --no-build --no-dependencies -c $env:CONFIGURATION -v m -o publish

# test:
#   assemblies:
#     - '**\*.tests.dll'

artifacts:
- path: '.\src\ILLightenComparer\publish\*.nupkg'
  name: nuget-package
  type: NuGetPackage

deploy:
- provider: Environment
  name: appveyor-nuget
  on:
    branch: master
