image: Ubuntu1804

version: 0.1.{build}

clone_depth: 1

configuration: release

branches:
  only:
  - develop
  - master

skip_tags: true

skip_branch_with_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  project: .\src\ILLightenComparer\ILLightenComparer.csproj

deploy:
- provider: Environment
  name: appveyor-nuget
  on:
    branch: master
